### ISSUE TITLE
We need timelines!

### ISSUE THREAD

**Issue by swarnap** [Nivenly/genderidentity.io#25]

**Comment by swarnap** [comment]
Overarching goal - website launch
What are the smaller milestones until then?
What are the post-launch activities/milestones?

**Comment by ellenkorbes** [comment]
Our MVP is an informative website with chat/forum sections, so here's my proposed timeline for that:

(I'll add all of these as separate issues as time allows.)

### Design timeline

- [ ] Choose a logo. #12 is in progress.
- [ ] Decide on our fonts and color palette, #17.
- [ ] Decide on a layout for the website. Nothing fancy for now.

### Front-end development timeline

- [ ] Decide on a CMS. (Jekyll PR is currently pending.) That'd be #10 and #15.
- [ ] Type up all the HTML+CSS+JS+etc. to implement all of the design section above.
- [ ] Get Rocket Chat installed, themed, and working. (This is the chat app.)
- [ ] Get Discourse installed, themed, and working. (This is the forum app.)
- [ ] Make sure the whole thing works fine together, is responsive, doesn't make your browser explode, etc.

### Content timeline

Here IMO the `About us` and `Support` sections of our [content structure document](https://github.com/Nivenly/genderidentity.io/blob/master/docs/content_structure.md) apply, and then the big, long articles can be done over time later. So, for now:

- [ ] About us
  - [ ] What is GenderIdentity.io?
  - [ ] Who are we? AKA Contributors
  - [ ] Volunteering AKA How can I help GI.io?
  - [ ] News (At first just a few posts about our progress.)
  - [ ] Contact us
- [ ] Support
  - [ ] Where do I start?
     - [ ] I think I’m trans.
     - [ ] My partner is trans.
     - [ ] A friend/family member is trans.
  - [ ] Support institutions (@kris-nova Should we mention our mysterious benefactor(s) here?)
  - [ ] Suicide hotlines

In addition:

- [ ] Draft a `Community Guidelines` document.
- [ ] Come up with some manner of recruiting for forum and chat mods/operators.

### Back-end timeline

- [ ] Make sure all of the above plays nice as a docker image.
- [ ] Kubernetes.
- [ ] Jenkins.
- [ ] Get it all up and running on a server somewhere.

### Marketing timeline

IMO this should apply *after* we've got something to show, but we should have it down before launch.

- [ ] Create social media accounts for the project.
- [ ] Decide on what our project's personality will be like on social media.
- [ ] Find or assign someone to manage our social media presences.
- [ ] Build up a cache of social media posts and auto-schedule them for posting, e.g. a bunch of images with pretty background pictures and relevant quotes (Like [this](https://s-media-cache-ak0.pinimg.com/originals/de/32/96/de32969cd22688a24b4d23d72ddaf173.jpg) maybe, I don't know.)
- [ ] So that the world knows about us:
  - [ ] Get in touch with relevant media outlets. (List?)
  - [ ] Get in touch with influential people in the trans community. (List?)
  - [ ] Potentially spend a small amount on advertising just to get the ball rolling.
- [ ] Set up a mailing list (I suggest [this](https://github.com/freeCodeCamp/Mail-for-Good)) people can sign up to.

Once everyone is done chiming in and this document is finalized, we move it to the /docs folder so it is its own file.
